### ISSUE TITLE
When running the dev server: TypeError [ERR_INVALID_ARG_TYPE]: The "strategy" argument must be of type object. Received type number (0)

### ISSUE THREAD

**Issue by idvorkin** [partykit/cursor-party#4]
Super fun project - I'm able to deploy it successfully in prod, but I'm hitting this on the dev server - any ideas? 

I'm getting an error trying to run the dev-server: 

``` bash 
npx partykit dev
🎈 PartyKit v0.0.0-1dfa367
---------------------------
Loading environment variables from .env
Build succeeded, starting server...
[pk:inf] Ready on http://0.0.0.0:56168
[pk:inf] - http://127.0.0.1:56168
[pk:inf] - http://10.1.10.203:56168
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [c] clear console, [x] to exit                                                                                                                 │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
file:///Users/idvorkin/rare_git/cursor-party/cursor-party/node_modules/partykit/dist/bin.mjs:94269
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "strategy" argument must be of type object. Received type number (0)
    at new ReadableStream (node:internal/webstreams/readablestream:254:5)
    at safeReadableStreamFrom (/Users/idvorkin/rare_git/cursor-party/cursor-party/node_modules/miniflare/dist/src/index.js:8391:10)
    at #handleLoopback (/Users/idvorkin/rare_git/cursor-party/cursor-party/node_modules/miniflare/dist/src/index.js:8553:36)
    at Server.emit (node:events:532:35)
    at parserOnIncoming (node:_http_server:1149:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by wip-abramson** [comment]
I also got this error

**Comment by staringispolite** [comment]
got this as well. any updates?
